import { toSnakeKey } from "@/lib/db/repos/mapping";
import { buildSeed } from "@/lib/db/seed-data";

// Render the demo dataset as D1 (SQLite) INSERT statements, printed to stdout —
// `pnpm --filter @studiobook/web db:seed-sql | wrangler d1 execute <db> --file -`
// (or piped straight to a file) seeds a fresh D1 database. The entity objects
// are the single source, so the SQL cannot drift from the app's types.

function sqlValue(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insertStatements(table: string, records: readonly object[]): string[] {
  return records.map((record) => {
    const entries = Object.entries(record as Record<string, unknown>);
    const columns = entries.map(([key]) => toSnakeKey(key));
    const values = entries.map(([, value]) => sqlValue(value));
    return `insert into ${table} (${columns.join(", ")}) values (${values.join(", ")});`;
  });
}

const seed = buildSeed();
const sections: [string, readonly object[]][] = [
  ["studios", [seed.studio]],
  ["studio_settings", [seed.settings]],
  ["members", seed.members],
  ["class_types", seed.classTypes],
  ["class_sessions", seed.sessions],
  ["bookings", seed.bookings],
  ["invoices", seed.invoices],
  ["invoice_line_items", seed.lineItems],
  ["notification_outbox", seed.outbox],
];

const lines: string[] = [
  "-- Studiobook demo seed. Generated by apps/web/scripts/emit-seed-sql.ts.",
  "",
];
for (const [table, records] of sections) {
  lines.push(...insertStatements(table, records), "");
}

console.log(lines.join("\n"));
