import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { toSnakeKey } from "@/lib/db/repos/mapping";
import { buildSeed } from "@/lib/db/seed-data";

// Render the demo dataset as Postgres INSERT statements for supabase/seed.sql
// (applied by `supabase db reset`). The entity objects are the single source, so
// the SQL cannot drift from the app's types.

function sqlValue(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insertStatements(table: string, records: readonly object[]): string[] {
  return records.map((record) => {
    const entries = Object.entries(record as Record<string, unknown>);
    const columns = entries.map(([key]) => toSnakeKey(key));
    const values = entries.map(([, value]) => sqlValue(value));
    return `insert into public.${table} (${columns.join(", ")}) values (${values.join(", ")});`;
  });
}

const seed = buildSeed();
const sections: [string, readonly object[]][] = [
  ["studios", [seed.studio]],
  ["studio_settings", [seed.settings]],
  ["members", seed.members],
  ["class_types", seed.classTypes],
  ["class_sessions", seed.sessions],
  ["bookings", seed.bookings],
  ["invoices", seed.invoices],
  ["invoice_line_items", seed.lineItems],
  ["notification_outbox", seed.outbox],
];

const lines: string[] = [
  "-- Studiobook demo seed. Generated by apps/web/scripts/emit-seed-sql.ts —",
  "-- run `pnpm --filter @studiobook/web db:seed-sql` to refresh.",
  "",
];
for (const [table, records] of sections) {
  lines.push(...insertStatements(table, records), "");
}

const outPath = resolve(dirname(fileURLToPath(import.meta.url)), "../../../supabase/seed.sql");
writeFileSync(outPath, `${lines.join("\n")}\n`);
console.log(`Studiobook: wrote ${outPath} (${lines.length} lines)`);
