import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildSeed } from "@/lib/db/seed-data";

// Render the demo dataset as SQLite statements for the D1-backed preview/prod
// database. Mirrors emit-seed-sql.ts (the Postgres/Supabase equivalent) but
// targets D1's dialect: booleans as 0/1, no schema qualifier, and a leading
// DELETE pass (in child-to-parent order) so re-running against an
// already-seeded database replaces the demo dataset instead of colliding with
// unique constraints. The entity objects are the single source, so the SQL
// cannot drift from the app's types.
//
// Usage: tsx scripts/emit-d1-seed-sql.ts <output-path>

function toSnakeKey(key: string): string {
  return key.replace(/[A-Z]/g, (char) => `_${char.toLowerCase()}`);
}

function sqlValue(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insertStatements(table: string, records: readonly object[]): string[] {
  return records.map((record) => {
    const entries = Object.entries(record as Record<string, unknown>);
    const columns = entries.map(([key]) => toSnakeKey(key));
    const values = entries.map(([, value]) => sqlValue(value));
    return `insert into ${table} (${columns.join(", ")}) values (${values.join(", ")});`;
  });
}

const outPath = process.argv[2];
if (!outPath) {
  console.error("usage: tsx scripts/emit-d1-seed-sql.ts <output-path>");
  process.exit(1);
}

const seed = buildSeed();
const sections: [string, readonly object[]][] = [
  ["studios", [seed.studio]],
  ["studio_settings", [seed.settings]],
  ["members", seed.members],
  ["class_types", seed.classTypes],
  ["class_sessions", seed.sessions],
  ["bookings", seed.bookings],
  ["invoices", seed.invoices],
  ["invoice_line_items", seed.lineItems],
  ["notification_outbox", seed.outbox],
];

const lines: string[] = [
  "-- Studiobook demo seed for D1. Generated by apps/web/scripts/emit-d1-seed-sql.ts.",
  "",
];
for (const [table] of [...sections].reverse()) {
  lines.push(`delete from ${table};`);
}
lines.push("");
for (const [table, records] of sections) {
  lines.push(...insertStatements(table, records), "");
}

writeFileSync(resolve(outPath), `${lines.join("\n")}\n`);
console.log(`Studiobook: wrote ${resolve(outPath)} (${lines.length} lines)`);
